<h1 class="heading">Registrace</h1>

<form method="post" class="setting">
    <ul>
        <li class="setting__item">
            <p class="setting__label">Přezdívka</p>
            <input class="setting__input" type="text" pattern=".{3,}" title="minimálně 3 znaky" name="nickname">
        </li>
        <li class="setting__item">
            <p class="setting__label">Heslo</p>
            <input class="setting__input" type="password" pattern=".{5,}" title="minimálně 5 znaků" name="password" /><br />
        </li>
    </ul>

    <div class="g-recaptcha" data-sitekey="6LeSJAATAAAAAK7u25rYNksRHwSpQfOD5j-c_2Fy"></div>

    <input class="setting__button" type="submit" value="Registrovat" />
</form>
