<h1 xmlns="http://www.w3.org/1999/html">Nastavení účtu <?= $user['nickname'] ?></h1>

<form method="post">

    Přezdívka: <br>
    <input type="text" value="<?= $user['nickname'] ?>" name="nickname"/><br/>

    Popisek: <br>
    <textarea name="description"><?= $user['description'] ?></textarea><br/>

    Motto: <br>
    <input type="text" value="<?= $user['motto'] ?>" maxlength="140" name="motto"/><br/>

    <br/>
    Webová stránka:
    <input type="text" value="<?= $user['website'] ?>" name="website"/>

    <br/>
    Facebook nick:
    <input type="text" value="<?= $user['facebook'] ?>" name="facebook"/>

    <br/>
    Twitter nick:
    <input type="text" value="<?= $user['twitter'] ?>" name="twitter"/>

    <br/>
    Google+ nick:
    <input type="text" value="<?= $user['googleplus'] ?>" name="googleplus"/>

    <input type="submit" value="Uložit informace" />
</form>