<?php if ($access) : ?>
    <nav class="nav">
        <ul class="nav__list">
            <li class="nav__item"><a class="nav__link" href="<?= Url::getAlias('admin') ?>/<?= Url::getAlias('account') ?>">Účet</a></li>
            <li class="nav__item"><a class="nav__link" href="<?= Url::getAlias('admin') ?>/<?= Url::getAlias('articles') ?>">Seznam článků</a></li>
            <li class="nav__item"><a class="nav__link" href="<?= Url::getAlias('admin') ?>/<?= Url::getAlias('editor') ?>">Editor článků</a></li>
            <?php if ($admin) : ?>
                <li class="nav__item"><a class="nav__link" href="<?= Url::getAlias('admin') ?>/<?= Url::getAlias('users') ?>">Správa uživatelů</a></li>
            <?php endif ?>
            <li class="nav__item"><a class="nav__link" href="<?= Url::getAlias('user')?>/<?= $userUrl ?>">Můj profil</a></li>
            <li class="nav__item"><a class="nav__link" href="<?= Url::getAlias('admin') ?>/<?= Url::getCommand('logout') ?>">Odhlásit se</a></li>
        </ul>
    </nav>
<?php endif ?>

<?php if ($access && !$admin) : ?>
    <p class="info">Nemáte administrátorská oprávnění, požádejte administrátora webu, aby vám je přidělil.</p>
<?php endif ?>

<?php $this->subController->printView(); ?>