<h1><?= $heading ?></h1>
<table>
    <?php foreach ($articles as $article) : ?>
        <tr>
            <td>
                <h2><a href="<?= Url::getAlias('article') ?>/<?= $article['url'] ?>"><?= $article['title'] ?></a></h2>
                <?= $article['description'] ?>
                <br>
                ID článku <?= $article['articles_id'] ?>
                <br>
                autor <?= $article['nickname'] ?>
                <?php if ($admin OR $article['author_id'] == $user['users_id']): ?>
                    <br/>
                    <a href="<?= Url::getAlias('admin') ?>/<?= Url::getAlias('editor') ?>/<?= $article['url'] ?>">Editovat</a>
                <?php endif ?>
                <?php if ($admin): ?>
                    <a href="<?= Url::getAlias('admin') ?>/<?= Url::getAlias('article') ?>/<?= $article['url'] ?>/<?= Url::getCommand('delete') ?>">Odstranit</a>
                <?php endif ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>