<!DOCTYPE html>
<html lang="cs-cz">
<head>
    <base href="/"/>
    <meta charset="UTF-8"/>
    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>"/>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600,300&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/style.css" type="text/css"/>
</head>

<body>
<header>
    <nav class="nav">
        <ul class="nav__list">
            <li class="nav__item"><a class="nav__link" href="<?= Url::getAlias('articles') ?>">Články</a></li>
            <li class="nav__item"><a class="nav__link" href="<?= Url::getAlias('users') ?>">Uživatelé</a></li>
            <?php if($login): ?>
                <li class="nav__item"><a class="nav__link" href="<?= Url::getAlias('admin') ?>">Administrace</a></li>
            <?php else: ?>
                <li class="nav__item"><a class="nav__link" href="<?= Url::getAlias('admin') ?>/<?= Url::getAlias('login') ?>">Přihlášení</a></li>
                <li class="nav__item"><a class="nav__link" href="<?= Url::getAlias('admin') ?>/<?= Url::getAlias('register') ?>">Registrace</a></li>
            <?php endif ?>
        </ul>
    </nav>
</header>

<?php foreach ($notices as $notice) : ?>
    <p class="notice"><?= $notice ?></p>
<?php endforeach ?>

<main class="main">
    <?php $this->controller->printView(); ?>
</main>

<script src="https://www.google.com/recaptcha/api.js"></script>
</body>
</html>