<!DOCTYPE html>
<html lang="cs-cz">
<head>
    <base href="/blog"/>
    <meta charset="UTF-8"/>
    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>"/>
    <link rel="stylesheet" href="css/style.css" type="text/css"/>
    <script src="https://www.google.com/recaptcha/api.js"></script>
</head>

<body>
<header>
    <h1>Blog</h1>
    <nav>
        <ul>
            <li><a href="<?= Url::getAlias('summary') ?>">Přehled</a></li>
            <li><a href="<?= Url::getAlias('articles') ?>">Články</a></li>
            <li><a href="<?= Url::getAlias('users') ?>">Uživatelé</a></li>
            <li><a href="<?= Url::getAlias('admin') ?>">Administrace</a></li>
        </ul>
    </nav>
</header>

<?php foreach ($notices as $notice) : ?>
    <p class="notice"><?= $notice ?></p>
<?php endforeach ?>

<article>
    <?php $this->controller->printView(); ?>
</article>
</body>
</html>