<h1 class="heading">Přihlášení do administrace</h1>

<form method="post" class="setting">
    <ul>
        <li class="setting__item">
            <p class="setting__label">Přezdívka</p>
            <input class="setting__input" type="text" name="nickname"/><br/>
        </li>
        <li class="setting__item">
            <p class="setting__label">Heslo</p>
            <input class="setting__input" type="password" name="password"/><br/>
        </li>
    </ul>

    <input class="setting__button" type="submit" value="Přihláslt"/>
</form>

<p class="info info--special">Pokud ještě nemáte účet, <a class="info__link" href="<?= Url::getAlias('admin') ?>/<?= Url::getAlias('register') ?>">zaregistrujte se</a>.</p>
