<div class="user">
<h1 class="heading">Profil uživatele <strong class="heading__no-style"><?= $user['nickname'] ?></strong></h1>

<?php if($user['admin']): ?>
    <p class="info info--special">administrátor</p>
<?php endif ?>

<?php if($user['description']): ?>
    <p class="user__description"><?= $user['description'] ?></p>
<?php else: ?>
    <p class="info info--warning">Uživatel ještě nemá žádný popis.</p>
<?php endif ?>

<?php if($user['description']): ?>
    <p class="user__motto"><?= $user['motto'] ?></p>
<?php else: ?>
    <p class="info info--warning">Uživatel ještě nemá žádné motto.</p>
<?php endif ?>

<?php if($user['website']): ?>
    <a class="user__link" href="<?= $user['website'] ?>" target="_blank">webová stránka</a>
<?php endif ?>

<?php if($user['facebook']): ?>
    <a class="user__link" href="http://facebook.com/<?= $user['facebook'] ?>" target="_blank">Facebook</a>
<?php endif ?>

<?php if($user['twitter']): ?>
    <a class="user__link" href="http://twitter.com/<?= $user['twitter'] ?>" target="_blank">Twitter</a>
<?php endif ?>

<?php if($user['googleplus']): ?>
    <a class="user__link" href="http://plus.google.com/+<?= $user['googleplus'] ?>" target="_blank">Google+</a>
<?php endif ?>

<h2 class="heading">Články uživatele</h2>
<ul class="list">
    <?php foreach ($articles as $article) : ?>
        <li class="article">
            <a class="article__title" href="<?= Url::getAlias('article') ?>/<?= $article['url'] ?>"><?= $article['title'] ?></a>
            <p class="article__author">Napsal <a class="article__user" href="<?= Url::getAlias('user') ?>/<?= $article['user_url'] ?>"><?= $article['nickname'] ?></a></p>

            <p class="article__description"><?= $article['description'] ?></p>

            <div class="article__admin">
                <?php if ($admin OR $article['author_id'] == $host['users_id']): ?>
                    <a class="option" href="<?= Url::getAlias('admin') ?>/<?= Url::getAlias('editor') ?>/<?= $article['url'] ?>">Editovat</a>
                <?php endif ?>
                <?php if ($admin): ?>
                    <a class="option" href="<?= Url::getAlias('admin') ?>/<?= Url::getAlias('article') ?>/<?= $article['url'] ?>/<?= Url::getCommand('delete') ?>">Odstranit</a>
                <?php endif ?>
            </div>
        </li>
    <?php endforeach ?>
</ul>
<?php if(empty($articles)): ?>
    <p class="info">Nebyl dosud přidán žádný článek. Nezírej a napiš nějaký!</p>
<?php endif ?>
</div>