<!DOCTYPE html>
<html lang="cs-cz">
<head>
    <base href="/blog"/>
    <meta charset="UTF-8"/>
    <title><?= $title ?> | tellus.cz</title>
    <meta name="description" content="<?= $description ?>"/>
    <link rel="stylesheet" href="css/style.css" type="text/css"/>
    <script src="https://www.google.com/recaptcha/api.js"></script>
</head>

<body>
<header>
    <h1>Blog</h1>
    <nav>
        <ul>
            <li><a href="<?= Url::getAlias('summary') ?>">Přehled</a></li>
            <li><a href="<?= Url::getAlias('article') ?>">Články</a></li>
            <li><a href="<?= Url::getAlias('user') ?>">Uživatelé</a></li>
            <li><a href="<?= Url::getAlias('admin') ?>">Administrace</a></li>
        </ul>
    </nav>
</header>

<?php foreach ($notices as $notice) : ?>
    <div class="notices">
        <p class="notice"><?= $notice ?></p>
    </div>
<?php endforeach ?>

<article>
    <?php $this->controller->printView(); ?>
</article>

<footer>
    <p>Ukázkový tutoriál pro jednoduché MVC z programátorské sociální sítě
        <a href="http://www.devbook.cz" target="_blank">devbook.cz</a>.</p>
</footer>
</body>
</html>