<h1>Seznam článků</h1>
<table>
    <?php foreach ($articles as $article) : ?>
        <tr>
            <td>
                <h2><a href="article/<?= $article['url'] ?>"><?= $article['title'] ?></a></h2>
                <?= $article['description'] ?>
                <?php if ($admin): ?>
                    <br />
                    <a href="editor/<?= $article['url'] ?>">Editovat</a>
                    <a href="article/<?= $article['url'] ?>/delete">Odstranit</a>
                <?php endif ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>